module.exports = {
  SECTION_PARAGRAPH: 'SECTION_PARAGRAPH',
  SECTION_DESCRIPTION: 'SECTION_DESCRIPTION',
  SECTION_IMPORT: 'SECTION_IMPORT',
  SECTION_USAGE: 'SECTION_USAGE',
  SECTION_EXAMPLE: 'SECTION_EXAMPLE',
  SECTION_RESULT: 'SECTION_RESULT',

  CONTENT_PARAMS: 'CONTENT_PARAMS',
  CONTENT_RETURN: 'CONTENT_RETURN',
  CONTENT_SCRIPT: 'CONTENT_SCRIPT',
  CONTENT_PARAGRAPH: 'CONTENT_PARAGRAPH',

  SCRIPT_JS: 'SCRIPT_JS',
  SCRIPT_JSON: 'SCRIPT_JSON'
};
