export default {
  SECTION_PARAMS: 'SECTION_PARAMS',
  SECTION_IMPORT: 'SECTION_IMPORT',
  SECTION_EXAMPLE: 'SECTION_EXAMPLE',
  SECTION_RESULT: 'SECTION_RESULT',

  CONTENT_PARAMS: 'CONTENT_PARAMS',
  CONTENT_SCRIPT: 'CONTENT_SCRIPT',

  SCRIPT_JS: 'SCRIPT_JS',
  SCRIPT_JSON: 'SCRIPT_JSON'
};
